# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:11:07+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import (
    NearEarthObject,
    NearEarthObjectList,
    SentryImpactRiskObject,
    SentryObjectPagingDto,
    Statistics,
)

app = MCPProxy(
    description='A web service for near earth objects. All the data is from the <a href="http://neo.jpl.nasa.gov/" target="_blank">NASA JPL Asteroid team</a>. \n\n \n\nNeoWs is proud to power AsteroidTracker on <a href="https://itunes.apple.com/us/app/asteroid-tracker/id689684901?mt=8" target="_blank">iOS</a> and <a href="https://play.google.com/store/apps/details?id=com.vitruviussoftware.bunifish.asteroidtracker&feature" target="_blank">Android</a> as well as related apps. \n\n Follow us on <a href="https://twitter.com/AsteroidTracker" target="_blank">Twitter</a>',
    title='NeoWs - (Near Earth Object Web Service)',
    version='1.0',
    servers=[{'url': 'http://www.neowsapp.com/'}],
)


@app.get(
    '/rest/v1/feed',
    description=""" Get a list of Near Earth Objects within a date range, The max range in one query is 7 days """,
    tags=['near_earth_object_information', 'neo_list_navigation'],
)
def retrieve_near_earth_object_feed(
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    detailed: Optional[bool] = None,
):
    """
    Find Near Earth Objects by date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/rest/v1/feed/today',
    description=""" Get a list of Near Earth Objects for today """,
    tags=['near_earth_object_information', 'neo_list_navigation'],
)
def retrieve_n_e_o_feed_today(detailed: Optional[bool] = None):
    """
    Find Near Earth Objects for today
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/rest/v1/neo/browse',
    description=""" Retieve a paginated list of Near Earth Objects """,
    tags=['near_earth_object_information', 'neo_list_navigation'],
)
def browse_near_earth_objects(page: Optional[int] = 0, size: Optional[int] = 20):
    """
    Browse the Near Earth Objects service
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/rest/v1/neo/sentry',
    description=""" Retrieves Near Earth Objects listed in the NASA sentry data set """,
    tags=[
        'near_earth_object_information',
        'neo_impact_risk_data',
        'neo_list_navigation',
    ],
)
def retrieve_sentry_risk_data(
    is_active: Optional[bool] = True, page: Optional[int] = 0, size: Optional[int] = 50
):
    """
    Retrieve Sentry (Impact Risk ) Near Earth Objects
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/rest/v1/neo/sentry/{asteroid_id}',
    description=""" Retrieves Sentry Near Earth Object by ID """,
    tags=['near_earth_object_information', 'neo_impact_risk_data'],
)
def retrieve_sentry_risk_data_by_id(asteroid_id: str):
    """
    Retrieve Sentry (Impact Risk ) Near Earth Objectby ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/rest/v1/neo/{asteroid_id}',
    description=""" Retrieve a Near Earth Objects with a given id """,
    tags=['near_earth_object_information', 'neo_impact_risk_data'],
)
def retrieve_near_earth_object_by_id(asteroid_id: str):
    """
    Find Near Earth Objects by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/rest/v1/stats',
    description=""" retrieveCurrentNeoStatistics """,
    tags=['neo_data_statistics'],
)
def retrieve_current_neo_statistics():
    """
    Get the Near Earth Object data set totals
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
