# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:11:07+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class EstimatedDiameter(BaseModel):
    estimated_diameter_max: Optional[float] = Field(
        None,
        description='An estimate of the maximum size of the Asteroid - bases on the abosolute magnitude',
    )
    estimated_diameter_min: Optional[float] = Field(
        None,
        description='An estimate of the minimum size of the Asteroid - bases on the abosolute magnitude',
    )


class EstimatedDiameterContainer(BaseModel):
    feet: Optional[EstimatedDiameter] = Field(
        None, description='estimated diameter feet'
    )
    kilometers: Optional[EstimatedDiameter] = Field(
        None, description='estimated diameter kilometer'
    )
    meters: Optional[EstimatedDiameter] = Field(
        None, description='estimated diameter meter'
    )
    miles: Optional[EstimatedDiameter] = Field(
        None, description='estimated diameter miles'
    )


class HashMapStringListNearEarthObject(RootModel[Any]):
    root: Any


class MissDistance(BaseModel):
    astronomical: Optional[str] = None
    kilometers: Optional[str] = None
    lunar: Optional[str] = None
    miles: Optional[str] = None


class NearEarthObjectList(BaseModel):
    element_count: Optional[int] = Field(None, description='Number of NEOs in list')
    links: Optional[Dict[str, Any]] = Field(
        None, description='Hypermedia links to collection'
    )
    near_earth_objects: Optional[HashMapStringListNearEarthObject] = Field(
        None, description='A collection of NearEarthObjects'
    )


class OrbitClassType(Enum):
    IEO = 'IEO'
    ATE = 'ATE'
    APO = 'APO'
    AMO = 'AMO'
    MCA = 'MCA'
    IMB = 'IMB'
    MBA = 'MBA'
    OMB = 'OMB'
    TJN = 'TJN'
    CEN = 'CEN'
    TNO = 'TNO'
    PAA = 'PAA'
    HYA = 'HYA'
    HYP = 'HYP'
    PAR = 'PAR'
    COM = 'COM'
    JFC = 'JFC'
    HTC = 'HTC'
    ETC = 'ETC'
    CTC = 'CTC'
    JFc = 'JFc'


class OrbitClass(BaseModel):
    orbit_class_description: Optional[str] = None
    orbit_class_range: Optional[str] = None
    orbit_class_type: Optional[OrbitClassType] = None


class OrbitalData(BaseModel):
    aphelion_distance: Optional[str] = None
    ascending_node_longitude: Optional[str] = None
    data_arc_in_days: Optional[int] = None
    eccentricity: Optional[str] = None
    epoch_osculation: Optional[str] = None
    equinox: Optional[str] = None
    first_observation_date: Optional[str] = None
    inclination: Optional[str] = None
    jupiter_tisserand_invariant: Optional[str] = None
    last_observation_date: Optional[str] = None
    mean_anomaly: Optional[str] = None
    mean_motion: Optional[str] = None
    minimum_orbit_intersection: Optional[str] = None
    observations_used: Optional[int] = None
    orbit_class: Optional[OrbitClass] = None
    orbit_determination_date: Optional[str] = None
    orbit_id: Optional[str] = None
    orbit_uncertainty: Optional[str] = None
    orbital_period: Optional[str] = None
    perihelion_argument: Optional[str] = None
    perihelion_distance: Optional[str] = None
    perihelion_time: Optional[str] = None
    semi_major_axis: Optional[str] = None


class PageMetaData(BaseModel):
    number: Optional[int] = None
    size: Optional[int] = None
    total_elements: Optional[int] = None
    total_pages: Optional[int] = None


class RelVelocity(BaseModel):
    kilometers_per_hour: Optional[str] = None
    miles_per_hour: Optional[str] = None


class SentryImpactRiskObject(BaseModel):
    Palermo_scale_max: Optional[str] = None
    absolute_magnitude: Optional[str] = None
    average_lunar_distance: Optional[float] = None
    designation: Optional[str] = None
    estimated_diameter: Optional[str] = None
    fullname: Optional[str] = None
    impact_probability: Optional[str] = None
    is_active_sentry_object: Optional[bool] = None
    last_obs: Optional[str] = None
    last_obs_jd: Optional[str] = None
    palermo_scale_ave: Optional[str] = None
    potential_impacts: Optional[str] = None
    removal_date: Optional[str] = None
    sentryId: Optional[str] = None
    torino_scale: Optional[str] = None
    v_infinity: Optional[str] = None
    year_range_max: Optional[str] = None
    year_range_min: Optional[str] = None


class SentryObjectPagingDto(BaseModel):
    links: Optional[Dict[str, Any]] = None
    page: Optional[PageMetaData] = None
    sentry_objects: Optional[List[SentryImpactRiskObject]] = None


class URL(BaseModel):
    authority: Optional[str] = None
    content: Optional[Dict[str, Any]] = None
    defaultPort: Optional[int] = None
    file: Optional[str] = None
    host: Optional[str] = None
    path: Optional[str] = None
    port: Optional[int] = None
    protocol: Optional[str] = None
    query: Optional[str] = None
    ref: Optional[str] = None
    userInfo: Optional[str] = None


class CloseApproachData(BaseModel):
    close_approach_date: Optional[str] = None
    close_approach_date_full: Optional[str] = None
    epoch_date_close_approach: Optional[int] = None
    miss_distance: Optional[MissDistance] = None
    orbiting_body: Optional[str] = None
    relative_velocity: Optional[RelVelocity] = None


class NearEarthObject(BaseModel):
    absolute_magnitude_h: Optional[float] = Field(
        None, description='Is a measure of an asteroids brightness'
    )
    close_approach_data: Optional[List[CloseApproachData]] = Field(
        None, description='Close approach information of the Asteroid'
    )
    designation: Optional[str] = None
    estimated_diameter: Optional[EstimatedDiameterContainer] = Field(
        None,
        description='A collection of estimated diameters (kilometers, meters, miles, feet',
    )
    is_potentially_hazardous_asteroid: Optional[bool] = None
    is_sentry_object: Optional[bool] = None
    name: Optional[str] = None
    name_limited: Optional[str] = None
    nasa_jpl_url: Optional[str] = Field(
        None, description='A Link to the NASA JPL Small-Body Database website'
    )
    neo_reference_id: Optional[str] = Field(
        None,
        description='The reference ID of the Asteroid - This correlates to the SPK ID for the JPL NEO data',
    )
    orbital_data: Optional[OrbitalData] = Field(
        None, description='Orbital information of t1he asteroid'
    )
    sentry_data: Optional[str] = None


class Statistics(BaseModel):
    close_approach_count: Optional[int] = Field(
        None,
        description='Number of Close Approach listings across all NEOs listed in NeoWs',
    )
    last_updated: Optional[str] = Field(
        None, description='TimeStamp the last time the DB was updated'
    )
    nasa_jpl_url: Optional[URL] = None
    near_earth_object_count: Optional[int] = Field(
        None, description='Number of NearEarthObjects listed in NeoWs'
    )
    source: Optional[str] = None
